"""your message

Revision ID: 9f7f03a2a035
Revises: a28b72a32145
Create Date: 2026-01-08 17:29:38.850142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f7f03a2a035'
down_revision: Union[str, None] = 'a28b72a32145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariffs', sa.Column('price_ru', sa.String(), nullable=True))
    op.add_column('tariffs', sa.Column('price_en', sa.String(), nullable=True))
    op.add_column('tariffs', sa.Column('price_uz', sa.String(), nullable=True))
    op.add_column('tariffs', sa.Column('description_ru', sa.String(), nullable=True))
    op.add_column('tariffs', sa.Column('description_en', sa.String(), nullable=True))
    op.add_column('tariffs', sa.Column('description_uz', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tariffs', 'description_uz')
    op.drop_column('tariffs', 'description_en')
    op.drop_column('tariffs', 'description_ru')
    op.drop_column('tariffs', 'price_uz')
    op.drop_column('tariffs', 'price_en')
    op.drop_column('tariffs', 'price_ru')
    # ### end Alembic commands ###
